version: '3'

services:
  front:
    build:
      context: ./curriculo
      dockerfile: ../Dockerfile-local
    image: curriculo-front
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      HOSTNAME: "0.0.0.0"
      NODE_ENV: "development"
    volumes:
      - ./curriculo:/app

